load numpy package
Source: [YouTube video](https://www.youtube.com/watch?v=QUT1VHiLmmI&list=PL8HdPYdFEhGgTOpQKMGpvTaBLHPPsNx8o&index=14)

In [2]:
import numpy as np

In [17]:
# a = np.array([1, 2, 3])
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# get dimension
a.ndim
b.ndim

2

In [13]:
# get shape
a.shape

(3,)

In [14]:
# get type

In [18]:
a.dtype

dtype('int16')

In [25]:
# get item size (in bytes)
b.itemsize

8

In [28]:
# get total size
# a.size
# a.itemsize
a.size * a.itemsize

6

### Accessing/Changing specific elements, rows, columns, etc

In [30]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
# Get specific element [r, c]
a[0, -1]

7

In [35]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# get a specific column
a[:,1]

array([2, 9])

In [39]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:3]

array([2, 5])

In [46]:
# assigning values to a row
a[1, 5] = 20
print(a)

# assigning values to a column
a[:,2] = [5, 10]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


__3-D example__

In [48]:
b = [[[0, 1, 2],
     [3, 4, 5],
     [6, 7, 8]],
    [[9, 10, 11],
    [12, 13, 14],
    [15, 16, 17]],
    [[18, 19, 20],
    [21, 22, 23],
    [24, 25, 26]]]
print(b)

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]
